package com.example.jdbcdemo.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

import com.example.jdbcdemo.domain.Book;

public class BookManagerJDBC implements BookManager{
	
	private Connection connection;
	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	
	private String createTableBook = "CREATE TABLE Book(id bigint GENERATED BY DEFAULT AS IDENTITY, title varchar(30), author(40), price double)";

	private PreparedStatement addBookStmt;
	private PreparedStatement deleteAllBookStmt;
	private PreparedStatement getAllBookStmt;
	
	private Statement statement;
	
	public BookManagerJDBC() {
		try {
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();
			
			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
		
			boolean tableExists = false;
			
			while(rs.next()) {
				if ("Book".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}
			
			if (!tableExists) statement.executeUpdate(createTableBook);
			
//			addBookStmt = connection.prepareStatement(sql);
			deleteAllBookStmt = connection.prepareStatement("DELETE FROM Book");
			getAllBookStmt = connection.prepareStatement("SELECT id, title, author, price FROM Book");
		
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	Connection getConnection(){
		return connection;
	}
	
	@Override
	public int addBook(Book book) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int deleteBook(Book book) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public List<Book> getAllBooks() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List<Book> findByTitle() {
		// TODO Auto-generated method stub
		return null;
	}

}
